---
language: python
python: "2.7"

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.vagrant.d/boxes
    - $HOME/.ccache

sudo: required
dist: trusty

env:
  global:
    - VAGRANT_URL=https://releases.hashicorp.com/vagrant/1.8.1/vagrant_1.8.1_x86_64.deb
    - VAGRANT_SHA256SUM=ed0e1ae0f35aecd47e0b3dfb486a230984a08ceda3b371486add4d42714a693d
  matrix:
    - VM=ufs
    - VM=zfs

before_install:
  - sudo apt-get update
  - sudo apt-get install -y python-pip
  - sudo apt-get install -y rsync
  - curl -Lo vagrant.deb "${VAGRANT_URL}"
  - sha256sum vagrant.deb
  - echo "${VAGRANT_SHA256SUM}  vagrant.deb" | sha256sum -c
  - sudo dpkg -i vagrant.deb
  - sudo apt-get install -y libxslt-dev libxml2-dev libvirt-dev zlib1g-dev ruby-dev qemu-kvm libvirt-bin
  - vagrant plugin install vagrant-libvirt

install:
  - pip install ansible ansible-lint
  - ansible --version
  - ansible-lint --version
  - printf '[defaults]\nroles_path=../' > ansible.cfg
  - pushd tests
  # after `adduser travis libvirtd`, re-login is required to take effect, so run with sudo
  - sudo vagrant up --provider=libvirt --no-provision ${VM}
  - sudo vagrant provision ${VM} --provision-with bootstrap
  - popd

script:
  - ansible-playbook -i localhost, --syntax-check tests/test-${VM}.yml
  - ansible-lint tests/test-${VM}.yml
  - pushd tests
  # after `adduser travis libvirtd`, re-login is required to take effect, so run with sudo
  - travis_wait 40 sudo ./provision-ansible.sh
  - sudo vagrant provision ${VM} --provision-with test
  - popd

notifications:
  email: false
  webhooks: https://galaxy.ansible.com/api/v1/notifications/

