---
- name: poudriere has been installed
  pkgng:
    name=poudriere
    state=present

- name: dialog4ports has been installed
  pkgng:
    name=dialog4ports
    state=present

- name: /usr/ports/distfiles has been created
  file:
    path=/usr/ports/distfiles
    state=directory

- name: check zpool is available or not
  command: /sbin/zfs list -H -o name -p "{{ poudriere_zpool }}"
  register: zpool_available
  changed_when: False
  ignore_errors: True

- name: zpool has been configured when available
  lineinfile:
    line='ZPOOL="{{ poudriere_zpool }}"'
    dest=/usr/local/etc/poudriere.conf
  when: zpool_available.rc == 0

- name: git has been installed when portsmethod is git
  pkgng:
    name=git
    state=present
  when: '"{{ poudriere_portsmethod }}" == "git"'

- name: subversion has been installed when portsmethod is svn
  pkgng:
    name=subversion
    state=present
  when: '"{{ poudriere_portsmethod }}" in ["svn", "svn+http", "svn+https", "svn+ssh"]'

- name: default ports for poudriere has been initialized
  command: poudriere ports -c -p default -m "{{ poudriere_portsmethod }}"
  args:
    creates: /usr/local/poudriere/ports/default

- name: builder jail has been created
  command: poudriere jails -c -j "{{ poudriere_jail }}" -v "{{ poudriere_jailversion }}" -a amd64
  args:
    creates: '/usr/local/poudriere/jails/{{ poudriere_jail }}'
