- name: poudriere has been installed
  pkgng:
    name=poudriere
    state=present

- name: /usr/ports/distfiles has been created
  file:
    path=/usr/ports/distfiles
    state=directory

- name: check zpool is available or not
  command: /sbin/zfs list -H -o name -p "{{ zpool_name }}"
  register: zpool_available
  changed_when: False
  ignore_errors: True

- name: zpool has been configured when available
  lineinfile:
    line='ZPOOL="{{ zpool_name }}"'
    dest=/usr/local/etc/poudriere.conf
  when: zpool_available.rc == 0

- name: default ports for poudriere has been initialized
  command: poudriere ports -c -p default
  args:
    creates: /usr/local/poudriere/ports/default

- name: builder jail has been created
  command: poudriere jails -c -j {{ jail_name }} -v {{ base_version }} -a amd64
  args:
    creates: /usr/local/poudriere/jails/{{ jail_name }}
